### ISSUE TITLE
Get nticks to work with tickmode="array"

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#1011]
When plotting a large heatmap, it appears that placing all the text in the ticks produces a very slow plot.

For example:

```r

a <- matrix(rnorm(11), 10000, 10)
rownames(a) = paste("aaa", 1:nrow(a))
library(heatmaply)
p <- plot_ly(z = a, type = "heatmap",
		x = 1:ncol(a), y = 1:nrow(a),
		showlegend = FALSE, colors = viridis::viridis(100),
		    zmin = min(a), zmax = max(a)) # VERY fast!
p  %>%
      layout(    
        yaxis = list(
          tickvals = 1:nrow(a), 
		ticktext = rownames(a),
		nticks = 10, # has no effect
          showticklabels = TRUE
        )
      )
```

This can be made MUCH faster if using `showticklabels = FALSE`. The question is if there is a way to make it fast while still showing some of the text in the side-ticks (for example, if nticks would work it might help).

Thanks.

**Comment by cpsievert** [comment]
> This can be made MUCH faster if using showticklabels = FALSE

Generally speaking, trying to draw 10,000 labels is going to be slow ;)

As the docs say, `nticks` only has an effect when `tickmode='auto'`. Since you are specifying `ticktext/tickvals`, `tickmode` is set to `"array"`

What is your use-case? If you provide sensible values to `y`/`x`, plotly.js should draw a sensible subset of labels.

```r
```
