### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by sunwen2000** [ropensci/plotly#1398]
I tried to run the code as in the example, and got the following error:
```
> library(plotly)
> 
> set.seed(100)
> d <- diamonds[sample(nrow(diamonds), 1000), ]
> 
> p <- ggplot(data = d, aes(x = carat, y = price)) +
+   geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
+   geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)
Warning: Ignoring unknown aesthetics: text
> 
> p <- ggplotly(p)
Error: .onLoad failed in loadNamespace() for 'Cairo', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/xinyu.liu/Library/R/3.5/library/Cairo/libs/Cairo.so':
  dlopen(/Users/xinyu.liu/Library/R/3.5/library/Cairo/libs/Cairo.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Users/xinyu.liu/Library/R/3.5/library/Cairo/libs/Cairo.so
  Reason: image not found
```

**Comment by mschilli87** [comment]
How did you install `plotly`?
It seems when you installed it, cario was installed (as it should be) and found but since then it was (re-)moved.
If you uninstall `plotly` and try to install it again, it shoudl either find the new place of the cairo lib or complain that cairo is not installed (in which case you'd have to install it first).
This definitely doesn't look like a bug in `plotly` but rather an error on your side so I'd recommend a more general channel for further help.
