### ISSUE TITLE
size argument doesn't always map correctly to marker.size

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#1479]
A minimal example, this should render 10 points, but it only renders 1 currently

```r
plot_ly(x = 1:10, y = 1:10, size = I(30))
```

<img width="830" alt="screen shot 2019-03-06 at 4 53 39 pm" src="https://user-images.githubusercontent.com/1365941/53919708-76f6bb80-4030-11e9-8d7c-d63cfc41fb4d.png">

Note the current CRAN version (4.8.0) also has this problem

**Comment by mmgledhill** [comment]
Another example where marker size is incorrect. Confirmed Issue exists in current CRAN version and development version in github.

Suspect it occurs when data is not grouped together (ordered by color variable) since it looks ok when the data is grouped by color variable


`library(plotly)`
`library(data.table)`

`#plotly not sizing markers correctly`

`myiris<-data.table(iris)`

`#make one species distinctly different`
`#will use as sizing`
`myiris[Species=="virginica", Sepal.Width:=Sepal.Width/4]`

`sizeref <- 2.0 * max(iris$Sepal.Width) / (50**2)`

`#this version looks like it might be ok?`
`pg<-plot_ly(myiris,`
`                          x=1:nrow(iris),`
`                          y=~Sepal.Length,`
`                           type="scatter",`
`                           mode='markers',`
`                           text=~Sepal.Width,`
`                           color=~Species,`
`                           marker = list(size = ~Sepal.Width, opacity = 0.5, sizemode = 'area', sizeref = sizeref))`

`pg`
![size_ok](https://user-images.githubusercontent.com/11818724/53976592-97705580-40c4-11e9-97a5-351ceaa55750.png)

`#break by mixing Species, expect all virginica to be about 1/4 of others`
`myiris<-myiris[order(Sepal.Length)]`
`pg<-plot_ly(myiris,`
`            x=1:nrow(iris),`
`            y=~Sepal.Length,`
`            type="scatter",`
`            mode='markers',`
`            text=~Sepal.Width,`
`            color=~Species,`
`            marker = list(size = ~Sepal.Width, opacity = 0.5, sizemode = 'area', sizeref = sizeref))`

`pg`
![size_incorrect](https://user-images.githubusercontent.com/11818724/53976624-a820cb80-40c4-11e9-9638-2529233548ab.png)

**Comment by cpsievert** [comment]
I think this is due to a different bug that you can avoid by using `size` and `sizes` instead of using the plotly.js `marker` API directly, like:

```r
plot_ly(myiris,
        x=1:nrow(iris),
        y=~Sepal.Length,
        type="scatter",
        mode='markers',
        text=~Sepal.Width,
        color=~Species,
        size = ~Sepal.Width, sizes = c(10, 100) * 15)
```

**Comment by mmgledhill** [comment]
Thank you for the quick reply. 

Your solution looks like it corrects the sizing issue but now there are missing points (where size is expected to be the same as other visible points) when I apply it to real-world data. Probably related to issue you highlighted above?

If I use the marker api, I can see all points but need to sort data ahead of time to correct the sizing issues.

**Comment by cpsievert** [comment]
Yea, try using the approach I suggested on your real data with `devtools::install_github("ropensci/plotly#1480")` installed

**Comment by mmgledhill** [comment]
The development version of github definitely fixes the issue. Do you know when it will be released to CRAN? I'm trying to bundle with packrat when I deploy to Rconnect but it is still using the global CRAN version that is already installed even though the github version is in my packrat.lock file. Any advise?

**Comment by cpsievert** [comment]
Hopefully this week

**Comment by mmgledhill** [comment]
Saw that it was just deployed. You are awesome!
