### ISSUE TITLE
xaxis tickmode=“array” not working for date axis

### ISSUE THREAD

**Issue by ismirsehregal** [ropensci/plotly#1748]
I'd expect the following example to display only two dates on the x-axis. However, all dates are shown. Am I doing something wrong? Using plotly 4.9.2

First saw the issue [here](https://stackoverflow.com/questions/61158531/r-plotly-cant-get-xaxis-tickmode-array-working-for-dates/).

```
library(plotly)

df <- data.frame(x = c("2016-08-12", "2016-08-13", "2016-08-14", 
                       "2016-08-15", "2016-08-16"), index = 1:5, y = 1:5)

plot_ly(df, x = ~x, y = ~y, type = "scatter", mode = "markers") %>%
  layout(xaxis = list(
    tickmode = "array",
    tickvals = list("2016-08-12", "2016-08-16"),
    ticktext = list("2016-08-12", "2016-08-16")))
```

**Comment by cpsievert** [comment]
If you really want the tickvals/ticktext approach, you also need `type = "category"`.

The downside to that approach is that the ticks aren't updated on zoom...maybe you want [`nticks`](https://plotly.com/r/reference/#layout-xaxis-nticks) (or `dtick`) and [`tickformat`](https://plotly.com/r/reference/#layout-xaxis-tickformat)?

Closing since this is more a question than a bug or feature request
