### ISSUE TITLE
saving plotly plots locally?

### ISSUE THREAD

**Issue by vinhdizzo** [ropensci/plotly#294]
Hi,

When I plot outside of RStudio, the visualization opens on the default browser.  The relevant files are located in a temporary location.  What's the proper way to save the interactive visually locally?  That is, analogous to the pdf and png functions in R.  Would like to do that in order to embed elsewhere.

Thank you.

**Comment by cpsievert** [comment]
Have a look at the `plotly_IMAGE()` function

**Comment by vinhdizzo** [comment]
Thanks @cpsievert, but I was actually referring to saving the entire *interactive* visualization locally.  That is, the html file and the necessary js libraries.  That way, I could embed the visualization within another html or container file (hoping to do so with pptx).  Thanks.

**Comment by cpsievert** [comment]
Are you familiar with [__rmarkdown__](http://rmarkdown.rstudio.com/)? For HTML output, it creates standalone HTML by default, so you could use it to get a page with just the plot (but, of course, you can include more than just the plot). 

```r
download.file(
  "https://gist.githubusercontent.com/cpsievert/77a4f1c3b5cd383927b1/raw/46f650785e4e6c5ff3779e9bac4b6631637bf3ed/basic.Rmd",
  "basic.Rmd"
)
rmarkdown::render("basic.Rmd")
browseURL("basic.html")
```

**Comment by vinhdizzo** [comment]
Yes, know what it is but don't use it so often. If I use this approach, sounds like I have to create a separate Rmd file for each visualization that I'm interested in. Then render each to have it's own html. Then embed each html, perhaps as an iframe. Is this your recommendation?

Any way to hack and create an html in the working directory when a plotly visualization is created using plotly or ggplotly? Thanks.

**Comment by cpsievert** [comment]
Actually, `htmlwidgets::saveWidget()` is a more elegant way of saving a single plot as standalone HTML. For reasons [discussed here](https://github.com/ramnathv/htmlwidgets/issues/166), at least currently, plotly objects are not htmlwidget objects, so you'll have to convert the plotly object to a htmlwidget object with `plotly:::toWidget()`

```r
library(plotly)
p <- plot_ly(mtcars, x = mpg, y = disp, mode = "markers")
htmlwidgets::saveWidget(plotly:::toWidget(p), "index.html")
```

(BTW, when I want multiple plots in a single report, I just work from one Rmd, and don't bother saving each plot independently of the final output).

**Comment by cpsievert** [comment]
Another option is to use `Export -> Save as Web Page` in the RStudio viewer

![screen shot 2015-11-07 at 1 12 44 pm](https://cloud.githubusercontent.com/assets/1365941/11012983/664fa10e-8551-11e5-954d-92140c0b5a8a.png)

**Comment by vinhdizzo** [comment]
Thanks @cpsievert , `htmlwidgets::saveWidget` is precisely what I was looking for.

**Comment by kbeck527** [comment]
FYI, you might want to correct the error message that contradicts the above statement> p = plotlyStackedBar(features_no_tax, longFormat = TRUE, scaled = TRUE, maxRows = 400, ylabp = "Relative Abundance", outputDir = "./")
Subsetting table for 400 rows highest with highest median value
Generating scaled stacked bar plot
Using name as id variables
> htmlwidgets::saveWidget(as.widget(p), file = "stacked_bar_scaled.html")
Warning message:
'as.widget' is deprecated.
Use 'plot_ly' instead.
See help("Deprecated")

**Comment by cpsievert** [comment]
Thanks @kbeck527, `as.widget()` isn't necessary anymore -- I've updated the comment

**Comment by Victsz** [comment]
Running out of memory while plotting 200k+ points. And I tried editbin /LARGEADDRESSAWARE to fix ref to https://jonathanchang.org/coding/fixing-pandoc-out-of-memory-errors-on-windows/  , but still same problem.

And open web page locally and copy the temp html file instead of using htmlwidgets is fine, so if there is a way to get the temp local file URL by some function calls such that I don`t have to run htmlwidgets.

+ p<-subplot(mergerd, nrows = length(mergerd),shareX = T)
+ htmlwidgets::saveWidget(p,'test.html')
+ 
pandoc.exe: Out of memory
Error: pandoc document conversion failed with error 251
In addition: Warning message:
running command 'C:/PROGRA~2/Pandoc/pandoc +RTS -K512m -RTS C:\Users\victor\Documents\Stash\bumblebee\BumblebeeR\Bumblebee\Bumblebee\test.html --from markdown --output C:\Users\victor\Documents\Stash\bumblebee\BumblebeeR\Bumblebee\Bumblebee\test.html --self-contained --template C:\Users\victor\AppData\Local\Temp\1\RtmpyuOMkE\file3c05b6878d2.html' had status 251 
>
+ p<-subplot(mergerd, nrows = length(mergerd),shareX = T)
+ htmlwidgets::saveWidget(p,'test.html')
+ 
pandoc.exe: Out of memory
Error: pandoc document conversion failed with error 251
In addition: Warning message:
running command 'C:/PROGRA~2/Pandoc/pandoc +RTS -K512m -RTS C:\Users\victor\Documents\Stash\bumblebee\BumblebeeR\Bumblebee\Bumblebee\test.html --from markdown --output C:\Users\victor\Documents\Stash\bumblebee\BumblebeeR\Bumblebee\Bumblebee\test.html --self-contained --template C:\Users\victor\AppData\Local\Temp\1\RtmpyuOMkE\file3c05b6878d2.html' had status 251 
>

**Comment by lamatko** [comment]
You can also save it as a `png`, `jpeg` or `pdf` file by using `export()`:

    p <- plot_ly(...)
    export(p, file='image.png')

**Comment by piyushgkb** [comment]
`p <- plot_ly(...)
export(p, file='image.png')`

does not work as it says : Webgl is not supported by browser. But the browser I use does support Webgl. I however also installed phantomjs too! 

How does it work for you?

**Comment by Sergeich11** [comment]
htmlwidgets::saveWidget(as_widget(p), file = "test_plotly_widget.html") worked for me (CRAN plotly version, RStudio 1.0.143). Frustratingly, plotly commands work in R console to produce charts viewable in Explorer but in RStudio I get just the axes and no data plotted. Saving as html does not work in R console (requires pandoc) but works from RStudio.

**Comment by qaiseri79** [comment]
Is it possible for saveWidget to add custom js file for plotly to add some aditional functionality.
