### ISSUE TITLE
How to support large dataset?

### ISSUE THREAD

**Issue by dlmeduLi** [ropensci/plotly#297]
Thanks

**Comment by chriddyp** [comment]
hey @dlmeduLi - try the chart `type` `scattergl`. This chart type uses webgl instead of SVG for rendering, and can chart orders of magnitude more points. Here's an example with 52k points:

```
library(plotly)
p <- plot_ly(diamonds, type="scattergl", x = carat, y = price, text = paste("Clarity: ", clarity),
                 mode = "markers", color = carat, size = carat)
plotly_POST(p, 'scattergl-diamonds', 'overwrite')
```

The graph: https://plot.ly/~chriddyp/1741.embed

[![](https://plot.ly/~chriddyp/1741.png)](https://plot.ly/~chriddyp/1741.embed)

**Comment by dlmeduLi** [comment]
@chriddyp : Worked perfectly! Thank you so much.
