### ISSUE TITLE
plotly and d3heatmap interference

### ISSUE THREAD

**Issue by markdane** [ropensci/plotly#325]
The code below knits fine to create an HTML file with an interactive plotly graph followed by an interactive d3 heatmap. If the call to d3heatmap is before the ggplotly command, the d3heatmap only displays the dendrograms and not the heatmap. Is there a way I can intermix these 2 types of interactive methods?

```{r}
library(ggplot2)
library(d3heatmap)
library(plotly)

m <- matrix(1:25,nrow = 5,ncol = 5,dimnames = list(LETTERS[1:5],letters[1:5]))
df <- data.frame(m, stringsAsFactors = FALSE)

p <- ggplot(df,aes(x=a, y=b))+
  geom_point()

ggplotly(p)
d3heatmap(df)
```

I'm using the following R and package versions: plotly_2.0.4, rmarkdown_0.8.1, d3heatmap_0.6.1, knitr_1.11, ggplot2_1.0.1

R version 3.2.1 (2015-06-18) Platform: x86_64-apple-darwin13.4.0 (64-bit) Running under: OS X 10.9.5 (Mavericks)

**Comment by cpsievert** [comment]
It's currently kind of a mess if you want to print more than one htmlwidget in a chunk, but it should get better soon. In the meantime, you'll have to print them in separate chunks.

**Comment by markdane** [comment]
I really appreciate using the tools you guys have created. They are awesome.

I can work around this issue but just want to be clear that putting them in separate chunks doesn’t solve the problem.

Please let me know if this is the proper way to report the issue or if you’d prefer a response back on github or elsewhere.

Thank you,

Mark Dane

**Comment by cpsievert** [comment]
My apologies, I misunderstood the problem here. It seems to be an dependency management issue since I see `Uncaught TypeError: d3.tip is not a function` in my console. If you report the issue to @jcheng5 here he might know better https://github.com/rstudio/d3heatmap

**Comment by jcheng5** [comment]
@cpsievert Does plotly.js bundle its own copy of d3?

**Comment by jjallaire** [comment]
It looks to me like plotly does indeed bundle it's own copy of d3 since it's not declared here: https://github.com/ropensci/plotly/blob/master/inst/htmlwidgets/plotly.yaml

@cpsievert To ensure all the different widgets that require d3 play together nicely you should include d3 using the standard html dependencies mechanism, e.g. do something like this:

https://github.com/rstudio/d3heatmap/blob/master/inst/htmlwidgets/d3heatmap.yaml

If you need a newer version of d3 that's fine as the copy of d3 with the highest version number will be utilized.

**Comment by jcheng5** [comment]
That would definitely explain a lot. d3.tip is a d3 plugin, so if our copy of d3 and d3.tip loaded first, then plotly.js loaded and brought its own d3 then it wouldn't be surprising for our d3 changes to be undone.

**Comment by pmarais** [comment]
From a practical perspective in a `shiny` application, what would you suggest? Loading the libraries in order, `plotly` first and `d3heatmap` second? Or using the `d3heatmap::d3heatmap()` and `plotly::plot_ly()` convention and managing the order in which the graphs are loaded?

Is there an interim fix for the `plotly.yaml | d3heatmap.yaml`  file that I can implement that would allow me to run both in the same `shiny` application?

**Comment by cpsievert** [comment]
Thanks for the tips @jjallaire @jcheng5. @pmarais @markdane for temporary fix, you can `devtools::install_github("ropensci/plotly@fix/deps")`.

Right now I just added the d3 dependency, but plotlyjs has [quite a bit of dependencies](https://github.com/plotly/plotly.js/blob/master/package.json#L42-L80), @etpinard maybe we should document all of them to be on the safe side?

**Comment by etpinard** [comment]
> @etpinard maybe we should document all of them to be on the safe side?

All the plotly.js dependencies are bundled up in the dist version. You shouldn't need to worry about them.

**Comment by jjallaire** [comment]
The problem is that if those dependencies conflict with other JS libraries
included by other htmlwidgets then we will have the problem of 2 copies of
a given JS library loaded concurrently on a single page (that's exactly
what happened here for d3).

The core idea behind dependency resolution for htmlwidgets is that all
widgets cooperatively register what their dependencies are and then the
system takes the most recent version of each dependencies. This does impose
some additional version sensitivity to dependencies (i.e. you need to be
able to work with forward versions) but the payoff of being able to
seamlessly mix widgets with arbitrary dependencies is huge.

So I think you should definitely register all plotly dependencies using the
standard htmlwidgets infrastructure or we'll likely continue to see
incompatibilities like the one we did with d3heatmap.

**Comment by etpinard** [comment]
Ok. 

Here are the plotly.js dependencies: https://github.com/plotly/plotly.js/blob/master/package.json#L42-L80

Apart from `d3` I doubt that any other plotly.js dependency will conflict with yours.

**Comment by cpsievert** [comment]
Thanks @jjallaire. All dependencies are now included in eeee7c0

**Comment by jjallaire** [comment]
What do you mean by "yours"?   The dependencies that plotly will need to
manage conflicts against are all of the JS libraries *ever used* by any
htmlwidget.

There are 58 widgets listed here: http://gallery.htmlwidgets.org/. Are the
plotly dependencies so idiosyncratic that none of these 58 other widgets
will ever use any of these libraries?

I realize it would be probably be unacceptably disruptive to break all of
these out into proper html dependencies right now, but know that each one
that isn't is a potential compatibility problem down the road (to the
extent that loading two different copies/versions of a JS library creates
problems).

We have a tool (htmlwidgets::scaffoldWidget) that will automatically create
the right package structure (download the dependencies and create a yaml
file that points to them) from a bower package. Is there a plotly bower
package that declares all of it's dependencies which might make this easier?

**Comment by jjallaire** [comment]
One issue here is that all of the dependencies are satisfied using the same
script (plotly-latest.min.js). In practice I think this means that
conflicts are still possible since plotly will *always* load all of it's
dependencies given the single script they reside in. Is it straightforward
to have each of these dependencies in their own script?

I realize that this could have a negative impact on load time for at least
the case of Shiny applications (in rmarkdown documents they'll all end up
in embedded).

@jcheng5 or @ramnathv Any thoughts on how to handle this?

**Comment by jcheng5** [comment]
I think first we should take a step back and figure out why the two d3 versions are stomping on each other. Taking a look at dist/plotly.js it looks like it is using AMD for everything and I don't see a global variable d3 being defined (although there clearly is; empirically, if you render a plotly widget by itself there's a window.d3 defined). If there is a way to "noconflict" the global away, I don't think it would affect other instances of d3 in the page.

Bostock makes a recommendation [here](https://github.com/mbostock/d3/issues/2219) but I'm not conversant enough in AMD to fully grok it.

Similarly for the other dependencies; if they just provide functionality through AMD and don't mess with global browser state, I think we could convince ourselves that it's not possible for them to break when loaded multiple times.

**Comment by jcheng5** [comment]
Oh, [there's the global](https://github.com/tbranyen/d3/commit/7f2d63e3c2394716833e7dd2f367d083884c6823), apparently.

**Comment by ramnathv** [comment]
I would agree with @jcheng5. As long as the dependencies bundled by `plotly` don't mess with globals, we should be good. Other than `d3` and `topojson`, I don't see any other significantly big dependencies that might cause global conflicts. As a result, I think having three dependencies `d3.min.js`, `topojson.min.js` and `plotly-nod3.min.js` makes sense. I would also take a look at including `topojson.min.js` as a conditional dependency, since it only gets used for maps (I believe).

@cpsievert it might be useful to add to your build script a line that generates a `plotly-nod3.min.js` which can then play well with `htmlwidgets`.

**Comment by ramnathv** [comment]
@jjallaire @jcheng5, this issue also highlights the need to build some assets on the `htmlwidgets` side that will help build widget-safe dependencies. My thoughts on this are far too abstract at this point, so let me see if I can write something up that we can then discuss.

**Comment by jcheng5** [comment]
@ramnathv Not trying to nit-pick you, but why do you say topojson might cause global conflicts? AFAIK it's just a bunch of functions?

**Comment by ramnathv** [comment]
I was not suggesting that  `topojson` will cause conflicts. Just saying that `topojson` is likely to be a dependency for other map based widgets like `leaflet`, `datamaps` etc. So factoring it out as a separate dependency might prevent it from being included multiple times.

**Comment by jcheng5** [comment]
Oh, OK, cool.

**Comment by jcheng5** [comment]
FYI, removing `this.d3=no` plus the comma right before that, seems to fix it, as plotly's embedded d3 will no longer be made global. Here's the sed version:

```bash
sed -E -e "s/,this.d3=[a-zA-Z]+//g" -i .backup plotly-latest.min.js
```

**Comment by pmarais** [comment]
@cpsievert The `devtools::install_github("ropensci/plotly@fix/deps")` didn't work for me, as I got an error. I haven't recorded the error, my apologies, as I am on a deadline.

I did manage to get `d3heatmaps` working alongside `plotly` by rendering the d3heatMapOutout in a reactive UI environment similar to the following, on the `server.R` side:

```
library(shiny)
library(d3heatmap)

output$heatMap_UI <- renderUI({
    d3heatmapOutput("heatMap")
  })
  
  output$heatMap <- d3heatmap::renderD3heatmap({
    # Create the heatmap
    d1 <- d3heatmap::d3heatmap(DATA, scale="none",dendrogram = dendoGRAMoption)
    d1
  })
```

And using the `plotly::plot_ly()` convention as opposed to loading the library in the global environment.

```
output$graph_plotly <- plotly::renderPlotly({
    p <- plotly::plot_ly(x= xDATA, y= yDATA, data = DATA)
    p
  })
```

**Comment by cpsievert** [comment]
In #362, I'm building d3, topojson, and plotlyjs (w/o d3/topojson) with browserify, so that htmlwidgets can resolve dependencies.

Problem is that d3heatmap seems to break when using Plotly's (more recent) version of d3 [v3.5.6](https://github.com/ropensci/plotly/blob/fix/dependencies/inst/htmlwidgets/plotly.yaml#L2-L5) instead of [v3.5.3](https://github.com/rstudio/d3heatmap/blob/master/inst/htmlwidgets/d3heatmap.yaml#L2-L5). Is it possible to have two different widgets use different versions of the same dependency within the same page?

If not, maybe our best option is to not register dependencies (with htmlwidgets) and follow @jcheng5's solution to avoid exposing Plotly's embedded d3. This will only be necessary in the short term, since plotly.js won't expose d3 as a global anymore once it reaches this milestone https://github.com/plotly/plotly.js/milestones/Modular%20plotly.js

(There will also be a way to tell 'modular plotly.js' to use a global d3, if one is already defined)

**Comment by jcheng5** [comment]
Can you give me a repro case for d3heatmap not behaving with d3 3.5.6? I upgraded on my local copy and didn't see any obvious issues.

(It's not possible to have two different htmlwidgets use different versions of the same dependency at this time.)

**Comment by cpsievert** [comment]
You'll need `devtools::install_github("ropensci/plotly@fix/dependencies")`

http://bl.ocks.org/cpsievert/a029e47bd9a9fd97a3ba

**Comment by jcheng5** [comment]
It's not the version of d3 that's the problem; it's that the d3.tip plugin is still being removed. Can I see an un-minified version plotly-x.js?

**Comment by cpsievert** [comment]
@jcheng5 https://raw.githubusercontent.com/ropensci/plotly/fix/dependencies/inst/htmlwidgets/lib/plotlyjs/plotly-x.js

**Comment by cpsievert** [comment]
This appears to have resolved itself. I suspect the first modular release of plotly.js did the trick -- https://github.com/plotly/plotly.js/releases/tag/v1.5.0
