### ISSUE TITLE
group should not create multiple traces

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#381]
The `group` argument in `plot_ly()` should probably be [translated the same way as ggplot2's group aesthetic](https://github.com/ropensci/plotly/wiki/ggplotly-design,-internals,-technical-stuff).

Among other things, this would make it easier to create candlestick charts requested in #351

**Comment by pstoyanov** [comment]
I don't know if you are referring to the same issue but it seems that `color` and `symbol` create a new trace too, which is very different from `ggplot`. `ggplotly` lumps `color` and `symbol` together to form a new aesthetic. I asked a question on SO about it: http://stackoverflow.com/questions/34582584/how-to-simultaneously-apply-color-shape-size-in-a-scatter-plot

Don't know if this is intentional, I am still very new to plotly.

**Comment by alyst** [comment]
+1: looks like `group` overrides `color` argument

**Comment by alyst** [comment]
@cpsievert  I would like to fix this, but at the moment I don't have a good understanding of R plotly and plotly.js internals. It looks like the colors are not assigned in `traceify()`; does it at all happen in R or in plotply.js? Could you please give me some clues where to look? TIA!

**Comment by cpsievert** [comment]
Closed via d2bf2a1eb56d824a091e2cc9afea09a5968dd050.
