### ISSUE TITLE
"Save and edit plot" link doesn't open browser from RStudio viewer

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#440]
not sure why

**Comment by cpsievert** [comment]
It has to do with RStudio's security restrictions. My workaround for the new "collaboration" button is to trigger an alert with a link to the plotly for R book:

![screen shot 2017-04-06 at 6 29 21 pm](https://cloud.githubusercontent.com/assets/1365941/24779721/b3072912-1af7-11e7-857e-f76e1a021fa9.png)

Closing since the save/edit button isn't included by default anymore, and so IMO isn't worth worrying about
