### ISSUE TITLE
update ticks on zoom for ggplotly()

### ISSUE THREAD

**Issue by em2287** [ropensci/plotly#485]
After updating plotly (to current git head) and ggplot2 to 2.1.0, I noticed that the scale labels no longer update when I zoom in.  For example, if I draw a zoom box between two adjacent labels, the resulting plot will have no labels on that axis.  Every plot with numeric axes is exhibiting this behavior.

If you can't reproduce, I'll try to track down exactly which update broke the labels.

**Comment by cpsievert** [comment]
Unfortunately this is something we'll have to be restricted to (at least for now). In order to do sizing correctly, and convert positional scales (i.e., x/y axes) faithfully, I'm sending `tickvals`/`ticktext` to plotly.js, but it's (not currently) possible to generate new tick labels on zoom in that case. I see two possible future directions:

(1) Add an argument to `ggplotly()`, or a postprocess function, which essentially says: "Don't use ticktext/tickvals and let plotly.js come up with the tick text/labels"
(2) Convince the plotly.js team it's worthwhile to add new spec for generating sensible ticks on zoom when ticktext/tickvals is supplied.

cc @etpinard @timelyportfolio

**Comment by Henry-E** [comment]
Any update on this?

**Comment by cpsievert** [comment]
Fixed by a61b605
