### ISSUE TITLE
[Documentation] Incomplete shiny plotly integration example

### ISSUE THREAD

**Issue by MySchizoBuddy** [ropensci/plotly#583]
The shiny-plotly example about [diamonds facet plots](https://plot.ly/r/shinyapp-explore-diamonds/) has an input slider named height of plot which doesn't do anything. The server.R code doesn't use it anywhere. Either remove that slider or show us how to change the plot height using the slider

Also pageWithSidebar() is deprecated you have to use fluidPage instead

**Comment by cpsievert** [comment]
Thanks. Moved to https://github.com/plotly/documentation/issues/385

**Comment by timelyportfolio** [comment]
@cpsievert, while this is a documentation problem, I think we might also have either a bug or confusing situation.  For instance, if we simplify this example as below.

```
library(shiny)
library(plotly)
data(diamonds, package = "ggplot2")

nms <- names(diamonds)

ui <- shinyUI(pageWithSidebar(
  
  headerPanel("Diamonds Explorer"),
  
  sidebarPanel(
    
    sliderInput('sampleSize', 'Sample Size', min = 1, max = nrow(diamonds),
                value = 1000, step = 500, round = 0),
    
    selectInput('x', 'X', choices = nms, selected = "carat"),
    selectInput('y', 'Y', choices = nms, selected = "price"),
    selectInput('color', 'Color', choices = nms, selected = "clarity"),
    sliderInput('plotHeight', 'Height of plot (in pixels)', 
                min = 100, max = 2000, value = 1000)
  ),
  
  mainPanel(
    plotlyOutput('trendPlot', height = "800px")
  )
))

server <- function(input, output, session) {
  
  #add reactive data information. Dataset = built in diamonds data
  dataset <- reactive({
    diamonds[sample(nrow(diamonds), input$sampleSize),]
  })
  
  output$trendPlot <- renderPlotly({
    
    # build graph with ggplot syntax
    p <- ggplot(dataset(), aes_string(x = input$x, y = input$y, color = input$color)) + 
      geom_point()
    
    # if at least one facet column/row is specified, add it
    #facets <- paste(input$facet_row, '~', input$facet_col)
    #if (facets != '. ~ .') p <- p + facet_grid(facets)
    # return the ggplot object and renderPlotly() will know how to handle it
    height = input$plotHeight
    print(height)
    ggp<-as.widget(ggplotly(p,height=height)%>%layout(autosize=TRUE))
    ggp$x$layout$height=height
    ggp
  })
  
}

shinyApp(ui,server)
```

In the code, the user is required to do two things to make this work.

1. do ` %>% layout(autosize=TRUE))` which does not make a whole lot of sense given that we are providing a new `height`
2. set `ggp$x$layout$height=height` since setting the `height` as documented in `?ggplotly` has no impact in Shiny contexts.  However, `height` in `ggplotly` seems to work as expected in non-Shiny contexts.

I'm still getting a feel for all the magic that is happening, so I have probably gotten a lot wrong here, and feel free to correct all my mistakes :)

**Comment by cpsievert** [comment]
Huh, I can fix (2) pretty easily, but (1) has me stumped at the moment. Could you file a new issue with the content you have here? I'll fix it once I know what's going on here -> https://github.com/plotly/plotly.js/issues/537
