### ISSUE TITLE
Provide a way to directly specify discrete data -> visual mapping

### ISSUE THREAD

**Issue by cldougl** [ropensci/plotly#678]
User had issue in her shiny app with a scatter plot that was colored by group (i.e. males // females). She was adding points incrementally and the color was not applied until at least one point from each group (at least 1 male + 1 female) were plotted. 
cc @cpsievert (previously discussed problem)

**Comment by cpsievert** [comment]
When `color` is discrete, and the number of `colors` is larger than the number of unique data values, the default behavior is the same as `scales::col_factor`:

> If the palette is discrete and has a different number of colors than the number of factors, interpolation is used.

So, this would (correctly, but perhaps, surprisingly) yield purple points:

```r
plot_ly(mtcars, x = ~mpg, y = ~disp, color = "male", colors = c("red", "blue"))
```

This brings up an important current limitation: there is no way to directly specify the domain -> range mapping (for color, as well as shape/linetype). I'm thinking it should be possible to specify this mapping by using the names of the character vector: 

```r
plot_ly(mtcars, x = ~mpg, y = ~disp, color = "male", colors = c(female = "red", male = "blue"))
```

This would ensure you get blue (instead of purple) points.
