### ISSUE TITLE
Return plot and trace ID with event_data

### ISSUE THREAD

**Issue by happyshows** [ropensci/plotly#730]
Hi,

I'm getting the following data point from a geom_bar chart when I click the brownish box on the plot. I was expecting plotly to return like x/y axis label, value of the selected box, value of the selected bar.

I could send x=4 into the react_dataset to get the xaxis name, but I feel it's a bit redundant and also subject to mistake if I have applied some unique sorting rule on the axis.

```
  curveNumber pointNumber x  y
1           1           0 4 19
```

![untitled](https://cloud.githubusercontent.com/assets/3208181/18852716/55f62070-8407-11e6-8cf4-db91ffd59143.png)

Is this possible within this package?

**Comment by cpsievert** [comment]
>  I was expecting plotly to return like x/y axis label, value of the selected box, value of the selected bar.

I'm not sure what you mean, could you be more precise?

**Comment by happyshows** [comment]
Hi,

I was expecting the event to return x-axis label, total value of the stacked bar (for this case) and other applicable, descriptive measures for a data point. 

currently, if i want to find out the x label, I'll need to pass the x=4 into the source dataset and lookup the 4th value.  However, it could be tedious and erroneous to find out when sorting , faceting is applied.

**Comment by cpsievert** [comment]
We let plotly.js do the bar stacking in this case, so I don't think it will ever be possible to directly return stacked values. Once we can explicitly set bar widths/heights in plotly.js, that might change...

That being said, you could do something like this (Disclaimer: this digs into the internals of ggplot2, so it could break)

```r
p <- ggplot(mtcars, aes(factor(vs), fill = factor(cyl))) + geom_bar()
# assuming 2 is the selected x-value
ggplotly(p, originalData = FALSE) %>% 
  plotly_data() %>% 
  filter(x == 2) %>% 
  summarise(sum(y))
```

For the x-axis tick text, I don't think I'll ever expose this information directly (for a number of reasons), but thinking about this problem has me convinced we should probably return both a plot ID and a trace ID so that users have a way to lookup this sort of information.

For now, assuming you have one x-axis with `tickvals`/`ticktext` (`ggplotly()` always uses `tickvals`/`ticktext`), you could do this:

```r
ax <- plotly_build(p)[["x"]]$layout$xaxis
# assuming 2 is the selected x-value
ax$ticktext[ax$tickvals == 2]
```

**Comment by cpsievert** [comment]
Seems like I gave some bad advice here, I'll soon be updating https://plotly-book.cpsievert.me/ with a section about this, but here is an example in the meantime:

```r
library(shiny)
library(dplyr)

ui <- fluidPage(
  plotlyOutput("bars"),
  verbatimTextOutput("click")
)

# if class were a factor, you'd need `levels()` here instead
classes <- sort(unique(mpg$class))

server <- function(input, output, session) {
  
  output$bars <- renderPlotly({
    ggplot(mpg, aes(class, fill = drv, customdata = drv)) + geom_bar()
  })
  
  output$click <- renderPrint({
    d <- event_data("plotly_click")
    if (is.null(d)) return("Click a bar")
    mpg %>%
      filter(drv %in% d$key) %>%
      filter(class %in% classes[d$x])
  })
  
}

shinyApp(ui, server)
```
