### ISSUE TITLE
plot_ly does not run, when some packages are not installed properly

### ISSUE THREAD

**Issue by kokitsuyuzaki** [ropensci/plotly#750]
Hi,

I examined this issue in detail.
https://github.com/ropensci/plotly/issues/732

I found that plot_ly can be interfered by some packages.

# Pattern.1 : R.utils
library("R.utils")
library("plotly")
plot_ly(z = ~volcano, type = "surface")

# Pattern.2 : ggplot2_2.1.0 × plotly_4.5.5.9000
devtools::install_github("ropensci/plotly", force=TRUE)
install.packages("ggplot2")
library(plotly)
plot_ly(z = ~volcano, type = "surface")

Both case, plot_ly does not run properly in my computer.
Please confirm it and make plotly package can be installed safely.

**Comment by cpsievert** [comment]
This is a problem with R.utils, see https://github.com/HenrikBengtsson/R.utils/issues/60

**Comment by HenrikBengtsson** [comment]
So, most likely a problem with lazyeval.  The following does not involve R.utils and gives the same error:
```r
> env <- NA  ## This is what lazyeval picks up internally
> library("plotly")
[...]
Warning message:
failed to assign NativeSymbolInfo for env since env is already defined in the ‘lazyeval’ namespace 
> plot_ly(z = ~volcano, type = "surface")
Error in .Call(env, f) : 
  first argument must be a string (of length 1) or native symbol reference
```
The reason you see this when R.utils is _attached_, is because it defines function `env()` and lazyeval gets confused just as in above example.
 
The workaround is to make sure to load the lazyeval package before anything else, that is, call `library("lazyeval")` the first thing you do in your script.

**Comment by kokitsuyuzaki** [comment]
Thanks!
