### ISSUE TITLE
Get embed_notebook() working inside nteract

### ISSUE THREAD

**Issue by jackparmer** [ropensci/plotly#768]
`embed_notebook()` currently doesn't work out-of-the-box in [nteract](https://nteract.io/)

Here's a screenshot of what you see currently:

![image](https://cloud.githubusercontent.com/assets/1865834/19629929/75c82af0-994d-11e6-9a1a-bb0a6569198c.png)

Here's a workaround currently being proposed for plotly.py on the Python side:

https://github.com/plotly/plotly.py/pull/562#issuecomment-245078317

**Comment by rgbkrk** [comment]
For those implementing this nteract accepts a payload when in the R kernel with mimetype `application/vnd.plotly.v1+json`:

```R
library(IRdisplay)

data <- list(list(x=c(1999, 2000, 2001, 2002), y=c(10, 15, 13, 17), type='scatter'))
figure <- list(data=data)

mimebundle <- list('application/vnd.plotly.v1+json'=figure)
#mimebundle[[]] <- figure
IRdisplay::publish_mimebundle(mimebundle)
```

It assumes the [Plotly figure from the Plotly JSON chart spec](http://help.plot.ly/json-chart-schema/). Result:

![screen shot 2016-10-23 at 8 18 41 pm](https://cloud.githubusercontent.com/assets/836375/19632677/e96e7de6-995d-11e6-94f7-9193aeca294d.png)

**Comment by souravsingh** [comment]
I would like to take a stab at this

**Comment by souravsingh** [comment]
How do I start with the issue?

**Comment by rgbkrk** [comment]
Within [embed_notebook](https://github.com/ropensci/plotly/blob/72904c36907bbfa5d0dec675165384e7f76f302c/R/print.R#L37) you'll want to use `IRDisplay` with `publish_mimebundle` as outlined above to embed the direct JSON (and likely the HTML as well). Feel free to cc me in your PR.

**Comment by cpsievert** [comment]
I was shocked/elated to find that Jupyter Notebooks appear to now have "native" support for _all_ [htmlwidgets](http://www.htmlwidgets.org/), which should [make a lot of folks happy](https://github.com/ramnathv/htmlwidgets/issues/144), and removes any need for a `embed_notebook()`-like hack. Here is a gif:

![jupyter](https://cloud.githubusercontent.com/assets/1365941/21372959/6e72012a-c6e0-11e6-8991-06982e4d8e8f.gif)

I'm guessing the notebook somehow knows to call [`repr::repr_html()`](https://github.com/IRkernel/repr/blob/6e1a943e4706e8044db228251bf46f201262b0e0/R/repr_htmlwidget.r#L12-L24) when the output is of class "htmlwidgets". It would be awesome if nteract could do something similar so printing htmlwidgets just works™️ in same way it does for other contexts (e.g., R console, rmarkdown, shiny, Jupyter, etc). 

PS. @rgbkrk's [suggested approach above](https://github.com/ropensci/plotly/issues/768#issuecomment-255639816) wouldn't lead to first-class support for a couple reasons 

(1) The R package has an extra layer of JavaScript that plotly.js doesn't know about -- meaning some R specific functionality (such as the [linked views](https://cpsievert.github.io/plotly_book/linking-views-without-shiny.html) stuff) wouldn't work.
(2) The R package bundles a specific version of plotly.js that might conflict with the version nteract uses.
(3) Requires the user to call an extraneous function to embed a plot.

@rgbkrk, I'd be happy to elaborate/discuss anything further to help nteract gain first-class support for all htmlwidgets, but @flying-sheep would probably be more helpful/knowledgable on that front. If and when that happens, we should probably deprecate `embed_notebook()`.

**Comment by rgbkrk** [comment]
> The R package has an extra layer of JavaScript that plotly.js doesn't know about -- meaning some R specific functionality (such as the linked views stuff) wouldn't work.

That's fine, it can keep on embedding HTML on the page. Does it require `define` and `require` to be available? The `require` "available" in the nteract app is the nodejs/commonjs require (and not suitable for use), which means that some amount of type checking is required (or a UMD bundle).

> The R package bundles a specific version of plotly.js that might conflict with the version nteract uses.

nteract's is at least namespaced, there is no global plotly object on the page. The bundled version allows for straight plotly spec -> render using jupyter's mimetype setup.

I'll upgrade my IRKernel setup to make sure I'm up to date and try this out.

**Comment by flying-sheep** [comment]
> I'm guessing the notebook somehow knows to call `repr::repr_html()` when the output is of class "htmlwidgets".

jep, that’s how I designed the IRkernel display system:

1. [`mime2repr`](https://irkernel.github.io/docs/repr/0.9/times-2repr.html) is a list of `repr_*` functions.
2. IRkernel basically calls all functions for the mimetypes returned by [getOption('jupyter.display_mimetypes')](https://irkernel.github.io/docs/IRdisplay/0.4.4/IRdisplay-options.html).
3. since those are S3 generics, the existence of a `repr_html.myclass` means that objects of class `myclass` will have this function called.

---

repr is explicitly designed not to be tied to IRkernel, so if anything wants to define a rich display/render system based on it, please go ahead!

**Comment by flying-sheep** [comment]
there’s one known bug idk how to work around: jupyter/notebook#1282

**Comment by cpsievert** [comment]
For those interested, with #859, one can now embed any (local) R plotly graph in *nteract* via `embed_notebook()` (remote coming soon):

![nteract](https://cloud.githubusercontent.com/assets/1365941/24114183/491ebd5e-0d6d-11e7-88e8-ba77efaac481.gif)

As it turns out, the problem is related to the fact that *nteract* doesn't wrap the resulting HTML in an iframe (but Jupyter does)...

Before officially closing this issue, it'd be nice to have a mechanism to tip off *nteract* users that they need to use `embed_notebook()` (maybe via a message when loading the package) -- @rgbkrk is there anyway to detect whether the R session in running in an *nteract* environment? Maybe (hopefully) through an environment variable?

**Comment by rgbkrk** [comment]
Jupyter doesn't put HTML in iframes unless instructed to. Everything has global access across the entire page. I actually wish that all HTML outputs were in null origin iframes.

There is no way to detect if an R session is running inside nteract, the jupyter notebook, or any other frontend (at least, not without doing JS/frontend fingerprinting...)

**Comment by jackparmer** [comment]
This works now on the dev. version 👍  
![image](https://cloud.githubusercontent.com/assets/1865834/24682577/54f8fade-1968-11e7-843f-a3f4ef0beeef.png)
