### ISSUE TITLE
Properties from second `add_trace()` are ignored

### ISSUE THREAD

**Issue by rtaggart** [ropensci/plotly#790]
In the example below, the `colors `and `sizes `attributes within `add_markers()` are ignored.
```
dat1 <- data.frame(x=1:10, y=rnorm(10))
dat2 <- data.frame(x=1:10, y=rnorm(10), group = c("g1", "g2"))


plot_ly() %>%
  add_lines(data = dat1, x=~x, y=~y, color = I("blue")) %>%
  add_markers(data = dat2, x=~x, y=~y, color = ~group, size = ~(abs(x)+1),
              colors = c("g1" = "green", "g2" = "red"),
              sizes = 30*c(1,4), inherit = FALSE)
```
If `add_lines(data = dat1, x=~x, y=~y, color = I("blue")) %>%` is removed, then the markers are rendered perfectly. The same issue occurs if `plot_ly()` is replaced with `plot_geo()`.

**Comment by cpsievert** [comment]
This is sort of a quirk/undocumented, but scales should be specified when initiating the object

```r
plot_ly(colors = c("g1" = "green", "g2" = "red"), sizes = 30*c(1,4)) %>%
    add_lines(data = dat1, x=~x, y=~y, color = I("blue")) %>%
    add_markers(data = dat2, x=~x, y=~y, color = ~group, size = ~(abs(x)+1))
```

**Comment by nitramwin** [comment]
@cpsievert I cannot believe I just now found this post. The `colors = c("g1" = "green", "g2" = "red") ` example has fixed a problem I have had since over two years!!! Perhaps this information could be added somewhere to an example. Btw, what would the routine be for symbols? `symbols = c("g1" = "circle", "g2" = "square")`
