### ISSUE TITLE
Axis category order for matrix-like plots

### ISSUE THREAD

**Issue by jrjhealey** [ropensci/plotly#863]
After updating plotly recently, the behaviour of the default heatmap label order seemed to have changed.

See this SO post for the full details: http://stackoverflow.com/questions/41231318/prevent-plot-ly-reordering-matrix

I have since rectified by problems by coercing the names to all follow the form Tree##, however I never did find out whether plotly supports specified ordering of columns (e.g. an option to tell it to use the ordering of the input matrix specifically).

If this exists and I've not found it, could you point me in the right direction as I've found nothing helpful so far.

If it doesn't, could you consider it as a feature request for future versions, to give more control over axis label ordering?

**Comment by cpsievert** [comment]
This was caused by a ([poorly documented](https://github.com/ropensci/plotly/blame/3d0e319f6eaa32221f379e200af11ff3bd68f7b5/NEWS.md#L234-L235)) intentional change. Just like in ggplot2, this change was intended to ensure categorical axis ordering either: (1) matches factor level ordering or (2) is sorted alphabetically (in the case of character strings). Thus, you *can* currently resolve the problem by ensuring the row/column names are factors:

```r
library(plotly)
m <- matrix(rnorm(20 * 20), nrow = 20, ncol = 20)

rs <- rownames(m, FALSE, "r")
rsf <- factor(rs, levels = rs)
cs <- colnames(m, FALSE, "c")
csf <- factor(cs, levels = cs)
plot_ly() %>%
  add_heatmap(z = ~m, x = csf, y = rsf)
```

![screen shot 2017-03-10 at 1 22 15 pm](https://cloud.githubusercontent.com/assets/1365941/23809780/99f280a2-0594-11e7-95e3-484987586e95.png)


That being said, I consider the current behavior when row/column names are strings to be a bug since the row/column names are reordered, but the `z` values aren't:

```r
plot_ly() %>%
  add_heatmap(z = ~m, x = cs, y = rs)
```

![screen shot 2017-03-10 at 1 20 32 pm](https://cloud.githubusercontent.com/assets/1365941/23809795/a0883178-0594-11e7-9529-21e9ae17bde1.png)


I see two ways to move forward:

(1) Reorder the `z` attribute appropriately.
(2) Avoid any reordering when a `z` attribute is provided (this issue is also relevant for surfaces).

The benefit of (1) is that the behavior would be consistent with other trace types (i.e., `"scatter"`), but it seems like you rarely would ever actually want that behavior, and doing it correctly in all cases seems hard, so I'm leaning towards (2).
