### ISSUE TITLE
ggplotly has recently broken with (at least) geom_bar

### ISSUE THREAD

**Issue by jacob-ogre** [ropensci/plotly#884]
I have a small dashboard ([here](https://cci-dev.org/shiny/open/fiveyr_review/)) that uses `ggplotly` with a `geom_bar.` Sometime recently - I don't know when - the combination stopped working: ggplot still renders fine, but using `ggplotly` breaks. The function call is:

```
renderPlotly({
  plt <- ggplot(df(), aes(category, count)) +
         geom_bar(stat = "identity") +
         theme_hc()
  ggplotly(plt)
})
```

And the stacktrace is:

```
Warning: Error in f: unused argument (<environment>)
Stack trace (innermost first):
    86: f
    85: layout$setup
    84: gg2list
    83: ggplotly.ggplot
    82: ggplotly
    81: ggplotly [<text>#16]
    80: func
    79: origRenderFunc
    78: output$out440c4bbcc41a0b94
     3: <Anonymous>
     2: do.call
     1: rmarkdown::run
```

I appreciate any thoughts / help on solving this.

**Comment by DavisVaughan** [comment]
I am experiencing a similar problem. I have not found a fix, but can offer a bit more insight into my debugging.

```
library(cranlogs)
library(ggplot2)
library(plotly)

dloads <- cran_downloads(packages = "tidyquant", from = "2016-12-31", to = as.character(Sys.Date()-1))
dloads_plot <-ggplot(dloads, aes(x = date, y = count)) + geom_line()
ggplotly(dloads_plot)
# Error in f(..., self = self) : unused argument (<environment>)
```

As jacob said, this fails at `ggplotly`. Using `debugonce(ggplotly)`, I can drill down to find that it fails on the call to `gg2list`. Specifically line 38 of the `gg2list` function with the code:

```
data <- layout$setup(layer_data, plot$data, plot$plot_env, 
plot$coordinates)
```

It seems that `layout$setup` is a ggproto object with an inner function `f`. That is where the `Error in f: unused argument (<environment>)` error is coming from. That inner function only has the following args:

```
function (self, data, plot_data = data.frame(), plot_env = emptyenv()) 
```

Is it a problem that we are passing `plot$coordinates` to `f`? I don't know enough about ggproto to give any feedback there, but when I removed `plot$coordinates` and ran just `layout$setup(layer_data, plot$data, plot$plot_env)` I was able to get a data frame returned. I was still not able to continue, however, because the next line of the `gg2list` function, `data <- layout$map(data)` failed as well.

Hopefully they can get this sorted out soon!

**Comment by cpsievert** [comment]
If you're using the CRAN version of ggplot2, you have to use the CRAN version of plotly.

If you're using the GitHub version of ggplot2, you have to use the GitHub version of plotly.
