### ISSUE TITLE
Ignoring explicitly provided widget ID; Shiny doesn't use them

### ISSUE THREAD

**Issue by komalsrathi** [ropensci/plotly#985]
I am using the current version of plotly and shiny. Whenever I am trying to create a plot, I am getting a warning:

```
Ignoring explicitly provided widget ID "fcfd29930da9"; Shiny doesn't use them
```

I have tested it with and without using plotly, and the warning seems to be associated with plotly.

Shiny and plotly versions:
```
plotly_4.6.0.9000
shiny_1.0.3
```

**Comment by cpsievert** [comment]
It should be safe to ignore this warning. I decided to add an id to avoid [this warning](https://github.com/rstudio/rmarkdown/issues/980) in rmarkdown documents, which in mind, is more annoying

**Comment by daattali** [comment]
@cpsievert is there any way to suppress this warning (without a global side effect like suppressing all warnings)?

**Comment by cpsievert** [comment]
This hack does the trick for now, but they should really merge this PR https://github.com/ramnathv/htmlwidgets/pull/265

```r
library(shiny)
library(plotly)

ui <- fluidPage(
  plotlyOutput("p")
)

server <- function(input, output, ...) {
  
  output$p <- renderPlotly({
    p <- plotly_build(qplot(1:10))
    p$elementId <- NULL
    p
  })
  
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
Awesome, as long as you don't think `p$elementId <- NULL` might breaks in a future date, I'm happy to use that :)

**Comment by simonsays1980** [comment]
While the warning has vanished with setting `elementId <-  NULL`, it produces probably another warning when stopping the app: 

`Warning message:
In rm(list = as.character(handle), pos = .wsconns) :
  object '4516200352' not found`

**Comment by vamsitroy** [comment]
hi,
using the above fix, I am still unable to generate a plot, a plot background just pops up without any kind of plot on it. please Advise.

**Comment by cpsievert** [comment]
@vamsitroy this workaround is no longer required with the dev version:

```r
devtools::install_github('ropensci/plotly')
```

**Comment by emrichter** [comment]
@cpsievert I downloaded the lastest dev version of plotly. I'm trying to test my shiny-app using shinytest.
It finds a difference between expected and current, since the elementId is everytime newly generated. Is there a workaround?
Thank in advance!

Here the screenshot:
![grafik](https://user-images.githubusercontent.com/36728688/36532723-cd4003fe-17c1-11e8-8b0c-e7ce0a634114.png)

**Comment by CDorich** [comment]
I'm having issues with passing the hover values to a variable, similar to; https://plot.ly/r/shiny-coupled-hover-events/  

# Hover over a raster and get the value for the raster as well as the X and Y cell value. 
 output$MainMap <- renderPlotly({
    
    # https://stackoverflow.com/questions/33227182/how-to-set-use-ggplot2-to-map-a-raster
      ggplot(data=tt, aes(y=y, x=x))  +
        geom_raster(aes(fill=r.1))  +
        theme_bw()  +
        coord_equal() + xlab("Longitude") + ylab("Latitude")  
    
  }) # this part works fine. 

# trying to just print the x,y,z values onto a separate plot. 
# eventual goal is to use the x, y point to grab that cell from a raster stack time series and plot the time series of the xy cell that is currently being hovered over. 

# pass hover data to a variable, 'textplot' the cell info for testing purposes. 
output$HoverSeries <- renderPlotly({
  eventdata <- event_data("plotly_hover") 
   validate(need(!is.null(eventdata), "Hover over the time series chart to populate this timeseries graph"))  
   
  # Get point number
  #datapoint <- as.numeric(eventdata$pointNumber) 
   eventdata <- eventdata[,3:5]
   textplot(eventdata )

})

# Getting the error mentioned at the start of this thread: 
# Ignoring explicitly provided widget ID "24281db6707f"; Shiny doesn't use them
#     output$HoverSeries <- renderPlotly({
  
# How can I get the hover value to pass to variable so that I can plot it...?
